node {
  
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
   
    git credentialsId: 'd4c9f0a2-c64d-4f06-9454-14fe80ff2be0', url: 'https://github.com/andreapaolinelli/sorgenti'
     
    
   }
  
     stage('Build') { // for display purposes
   
    //dotnetBuild project: 'ClassLibraryProjects', workDirectory: 'sorgenti'
    //dotnetBuild project: 'ClassLibraryProjects.sln'
    //dotnetBuild project: 'ClassLibraryProjects.sln', workDirectory: 'andreapaolinelli/sorgenti'
    //dotnetBuild project: 'ClassLibraryProjects.sln', sdk: 'versione 3', workDirectory: '/var/jenkins_home/workspace/progettoandrea'
       dotnetBuild project: 'ClassLibraryProjects.sln', sdk: 'versione 5.0.0', workDirectory: '/var/jenkins_home/workspace/progettoandrea'
     
       
    
   }
  
   stage('Uni_Test') { // for display purposes
     dotnetTest logger: 'trx;LogFileName=unit_tests.trx', project: 'ClassLibraryProjects.sln', sdk: 'versione 5.0.0', workDirectory: '/var/jenkins_home/workspace/progettoandrea'
     }
  
   stage('Junit_output') { // for display purposes
     mstest testResultsFile:"**/unit_tests.trx", keepLongStdio: true
     junit allowEmptyResults: true, testResults: 'StringLibraryTest/TestResults/unit_tests.trx'
     }
  
 
 
}
